---
image: debian:latest

before_script:
  - apt-get -y update
  - apt-get install -y python3-minimal python3-apt
  - python3 --version
  - python3 -m pip install ansible molecule[docker]  ansible-lint flake8
  - ansible --version
  - molecule --version
  - ansible-lint --version

molecule:
  variables:
    MOLECULE_DISTRO: centos:8
    MOLECULE_INSTANCE_NAME: Centos8
  stage: test
  script:
    - molecule test
