---
stages:
  - test

image: debian:latest

before_script:
  - apt-get update -y
  - apt-get install -y python3-minimal python3-apt python3-pip docker
  - python3 --version
  - pip3 install ansible molecule[docker] ansible-lint flake8 molecule-docker docker
  - ansible --version
  - molecule --version
  - ansible-lint --version

#
# Templates
#
.test:molecule: &molecule_test
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
    ROLE_NAME: vim
  script:
    - cd .. && ln -sf $CI_PROJECT_DIR $ROLE_NAME && cd $ROLE_NAME
    - molecule test

#
# Tests
#
molecule_centos_8:
  stage: test
  variables:
    MOLECULE_DISTRO: centos:8
    MOLECULE_INSTANCE_NAME: Centos-8
  <<: *molecule_test

molecule_debian_buster:
  stage: test
  variables:
    MOLECULE_DISTRO: debian:buster
    MOLECULE_INSTANCE_NAME: Debian-Buster 
  <<: *molecule_test

