---
image: centos:8

before_script:
  - yum install python3 docker
  - python3 --version
  - python3 -m pip install ansible molecule[docker]
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test
