---
image: centos:8

services:
  - centos:dind

before_script:
  - docker info
  - python3 --version
  - python3 -m pip install ansible molecule[docker]
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test
